### ISSUE TITLE
Improved way to load as conda virtual environment

### ISSUE THREAD

**Issue by pjgoodall** [chendaniely/pandas_for_everyone#13]
Hi Daniel,

Nice course!

This is working well  so-far
`% conda env create --name pandas_for_everyone -f environment.yml`

environment.yml:
``` yml
name: pandas-data-analysis-chen
channels:
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - python=3
  - pip
  - feather-format
  - ipython
  - jupyterlab
  - numba
  - numpy
  - odo
  - openpyxl
  - pandas
  - pandas-datareader
  - pweave
  - regex
  - scikit-learn
  - seaborn
  - statsmodels
  - wget
  - xlwt
```

Cheers,
--Peter G
